# Generated by Django 5.2.17 on 2026-09-21 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0146_remove_climatematch"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membershiprequests",
            options={
                "verbose_name": "Membership Request",
                "verbose_name_plural": "Membership Requests",
            },
        ),
    ]
