# Generated by Django 5.2.17 on 2026-09-28 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0147_alter_membershiprequests_options"),
        ("organization", "0147_organization_is_draft"),
    ]

    operations = []
